# Generated by Django 4.1.3 on 2022-11-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pokemon1', models.CharField(max_length=50)),
                ('pokemon2', models.CharField(max_length=50)),
                ('pokemon3', models.CharField(max_length=50)),
                ('pokemon4', models.CharField(max_length=50)),
                ('pokemon5', models.CharField(max_length=50)),
            ],
        ),
    ]
